spring.profiles: docker
server.port: 8080
spring.data.mongodb.host: mongodb
spring:
  data:
    mongodb:
      username: ${SPRING_DATA_MONGODB_USERNAME}
      password: ${SPRING_DATA_MONGODB_PASSWORD}
      authentication-database: ${SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE}
